apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: universal-auth-credentials
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: universal-auth-credentials
      secretsScope:
        projectSlug: gordito-t-qqz
        environmentSlug: dev
        secretsPath: /
        recursive: false
        expandSecretReferences: false
