apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synology-csi
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
secretGenerator:
  - name: synology-csi-client-info
    files:
      - client-info.yaml=synology-csi-client-info.sops.yaml
    type: Opaque
