apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - synology-csi-client-info.sops.yaml
patches:
  - path: patch-client-info.yaml
    target:
      kind: StatefulSet
      name: synology-csi-controller
