apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - controller.yml
  - node.yml
  - csi-driver.yml
  - storage-class.yml
  - secrets/client-info-external-secret.yaml
