apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: synology-csi-controller
  namespace: synology-csi
spec:
  template:
    spec:
      containers:
        - name: csi-plugin
          volumeMounts:
            - name: client-info
              mountPath: /etc/synology/client-info.yaml
              subPath: client-info.yml
              readOnly: true
