apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  dsm: "192.168.1.79"
  location: "/volume1"
  protocol: iscsi
reclaimPolicy: Delete
allowVolumeExpansion: true
