apiVersion: v1
kind: ConfigMap
metadata:
  name: ddns-updater-config
  namespace: ddns-updater
data:
  config.json: |
    {
      "settings": [
        {
          "provider": "cloudflare",
          "domain": "dimarco-server.site",
          "zone_identifier": "78b7dbb36e52a128d82358314dc3f92a",
          "host": "@",
          "ip_version": "ipv4",
          "ipv6_suffix": ""
        }
      ]
    }
