apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ddns-updater-credentials
  namespace: ddns-updater
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: ddns-updater-secret
  data:
    - secretKey: CONFIG
      remoteRef:
        key: /cloudflare/DDNS_CONFIG_JSON
