apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bytestash-credentials
  namespace: bytestash
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: bytestash-secret
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /bytestash/JWT_SECRET
