---
creation_rules:
  # Talhelper files
  - path_regex: .*\/(talsecret)(\.sops)?\.yaml
    encrypted_regex: "^(username|password|id|secret|bootstraptoken|secretboxencryptionsecret|token|ca|crt|key)$"
    key_groups:
      - age: ["age1y827m2r4ydam7xw0wv4s4tpjv63fwk0rnauzffdtt63pj4734c9q5w5g2j"]

  # Generic Kubernetes Secrets
  - path_regex: .*\.secret(\.sops)?\.yaml
    # encrypted_regex: "^(data|stringData|username|password)$"
    key_groups:
      - age: ["age1y827m2r4ydam7xw0wv4s4tpjv63fwk0rnauzffdtt63pj4734c9q5w5g2j"]
