apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-private
  namespace: flux-system
spec:
  interval: 5m
  url: ssh://git@github.com/octaviodimarco/homelab-private.git
  ref:
    branch: feature/tdarr
  secretRef:
    name: private-repo-deploy-key
  recurseSubmodules: true
