apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 30m
  chart:
    spec:
      chart: velero
      version: "5.*"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
      interval: 12h
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.1
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      provider: aws
    credentials:
      useSecret: true
      existingSecret: minio-credentials
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

