apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kasm
  namespace: kasm
spec:
  interval: 1h
  chart:
    spec:
      chart: kasm
      version: "1.1181.0"
      sourceRef:
        kind: HelmRepository
        name: kasm
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Deshabilitar componentes internos que usaremos externos
    postgresql:
      enabled: false
    redis:
      enabled: false
    
    # Storage
    persistence:
      storageClass: nfs-csi
    
    # Service - Must be ClusterIP when using ingress
    service:
      type: ClusterIP
    
    # Public Address
    publicAddr: kasm.dimarco-server.site
    
    # Ingress
    ingress:
      enabled: true
      tls: true
      backendProtocol: http
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.kubernetes.io/ignore: "true"
      labels: {}
  valuesFrom:
    - kind: ConfigMap
      name: kasm-values
    - kind: Secret
      name: kasm-helm-values

