apiVersion: v1
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
stringData:
    client-info.yml: ENC[AES256_GCM,data:fX0xKx9nwfRetiuadYVJ0A3uaYo0f6iZOlVDUspJBCyfFmr7ST1a105NCXZumUTBhQmi2E+SKUWtNZPkPVEn1p2KWdS5prCJRL1juM8sEopcSC12fENND6t8,iv:C2KT1dxqFLDtm+ZPHoW06BFVlkiE63vnI0Siz8dzTsU=,tag:GaJBP/a8pTePq6gEhne61A==,type:str]
sops:
    age:
        - recipient: age1pwdq0qxfnk5m2vgyhaqw4ya3clhjnf5s5y9khfluqsgtn04jmd4qxs0uky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UGFCdWZBaCtqektSU0Vz
            TjBpd0lWRGY2OExMODB2bGxweCtjSmMyYnljClBiV2txcTNlbjg5cWJqYStOajZu
            WExNS2VPeml4RXBjK2tVSEMwNmh3VlkKLS0tIHlWMTBaVDEvU3FiQ3BhV1ZOSE1t
            am41Zk1Nc3NGMkRGRlZYRXdjWW1MbzQKPXYd3Ho3rbW1G4Xffvbun8eqkKoymw+7
            TyX7iCp0tmPWzTksi5MFEmQrT8MtEzuu052IXOhM9Jg0rFBVfwTxrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T18:13:52Z"
    mac: ENC[AES256_GCM,data:/TO2lKBUidTFi8VLa5K4N4rhzerIs5TJ7gprbdi+Xc16gV71CdXbexjaSXWdEUeDgZFkEXef3i4DSvPBGaIVDVFCleM1N2dT8YRhm4lJMKEp7oSHFeBerFZDuYGjJo++UXzVPrXbhnsRLRxuCztKeSh5T+ucrZlumxqQ09tTvnk=,iv:074akGNEu/VhxYNhI9/M0C4JIG5zt3uX0Uy2e+UH2hM=,tag:iLpszgNYgj5+CKsoCP5v9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
