apiVersion: v1
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
stringData:
    client-info.yml: ENC[AES256_GCM,data:YOcpjHc57sdeT8/p2WVqkrl98BjlkbXEdql+T0Jz9hfeIsZOpiiWv0LUrba+W9nyNNXxE5bnvhIFxLK8Ob77x/5PYXgo4eqih9HgupzlrIL0mEG+Q6PV5ZPjKDV3fBtoYYuDVW/PDhO/OvGyUrb3Bi08LRLcB2I=,iv:pGzVvMQuTCJIwUywsIKzU8kBsp/mldwH/qPKqn2Bm7U=,tag:shDFEFRhK/tfVVZZG61ZLw==,type:str]
sops:
    age:
        - recipient: age1dqgm5tfej54xrt6627n4ru0xp0x5xav8nm0pk23zhxzgcxrpnp4qdm9rwc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROS9Jb296ZStickQ4YUg1
            Z05WQm9lYjRUZkxxeEdrUnJkbnBoVzIwRWk4CjJaa0xXMWdmVUZjMytIMHYvbmM2
            SGU3Y0FDY21DTWJvaW5xUWMwUEJqSTAKLS0tIGNpTi9wTG9KcmlsYzRkS0ttM3Qr
            MExIaXJxczhaSkl4RW1uKy9ibVpvb2sK+Vb+SOSCt2e+Tym3THanmjTNasKU4qLA
            gPcGY+JTs63lAf7R2PAfseB7aM/SJ2ybTIkYc+uK2Ln1r+MojosCCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T17:41:09Z"
    mac: ENC[AES256_GCM,data:VjDhonv3gKsVL+Ol8r2QobEdT6EOvp9ztcNW9GLzg9t6xMyt0mokotZ0thbHKJamQW31luaPVVXX4mxcuXhszFbk1dR1mjUB+ddxA6CD64vSyTv3KlG0AM6iXObuIZbSCcAJXNncoWTlYHCCYyBeFW0ttnDFQjWz8f+B7QebDNs=,iv:zqCYWVfwh+iseubH5JvYLWqhetlD1Y1eI2IeT36rbEo=,tag:sJ+0oBzVaGeQWqD+qHJhMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
