apiVersion: v1
kind: Secret
metadata:
  name: client-info-secret
  namespace: synology-csi
stringData:
  clients: ENC[AES256_GCM,data:1hAADTKxL+z/SLuiZIP7p+11xBZAeIsuVd3RKzk/ZHTp1fMQATSI/XnvFNXJpALw2O3ek+VFP8pW7SYKjmOj52ARDypWNr5GAfdZk3iFQQHO4Mhtu+dJWeNwOsf7HCBDect3tKBRP4U=,iv:xaXvmwVU7jpq5TQgpvtzhqA5bQQj02iWjw9k/gX++ds=,tag:c4077FKUMi8+hd8qE5/xKA==,type:str]
sops:
  age:
    - recipient: age1vy32958dn82naq7nw280x7v74tpgca66wgum5tac39cad47gddrqrh4qz8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZW9ldlZ6ZndOK0liME5C
        OTgzWWNRVW5uQmdkVEN2RVZzM203VStXQXlNCmZXQW95elpWNzBKNWFSL2dFeGZj
        QnN2Qno3OGE4RExvOExQdVowaWF4MzAKLS0tIGNUeHk2RFZFNU1JMWR1eFdjU25Z
        QXJpOC9aVitibmZzR2czU0dBU1AveUUKZnEfqjHwXBh4p2WVFzP2MgQEgc4QXUuA
        6QX3Gg0JhU6ZcG6lj0hUkq09LSvQm0z5tNCtrZ6s1WAvrPUkCChP9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-16T15:51:24Z"
  mac: ENC[AES256_GCM,data:4EpoIo9onej381RW64HTm2fu2HJWRnLRPc5bZOypFFhC+pWrZxDDHI1/CcNLFWFa7IqNqy7fi7DDW0BW9IbWi2FVLFQO0be75z7MmebkLqJ9V35qlH7//HpYQSipuWNJNP3abAWN7hBeMS/c8+YDtCLUB4DP80kG/CWLTjAcZXw=,iv:OAwUn7Fe16Owd/OHoXfNGqt2eUzePsvXSarzGtjFucU=,tag:uzAbKyggmUcJROdjymJ2Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
