apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: SOPS_AGE_KEY_FILE # Variable de entorno que SOPS usará para encontrar la clave
              value: /var/sops/age/key.txt # Ruta donde montaremos el archivo de la clave
          volumeMounts:
            - name: sops-age-key-volume # Nombre del volumen
              mountPath: /var/sops/age # Directorio donde se montará el Secret
              readOnly: true
      volumes:
        - name: sops-age-key-volume # Nombre del volumen (debe coincidir con volumeMounts)
          secret:
            secretName: sops-age-key # El Secret de Kubernetes que contiene tu clave Age
            items:
              - key: age.key # La clave dentro del Secret que contiene tu clave privada Age
                path: key.txt # El nombre del archivo dentro del volumen montado
