apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - mountPath: /etc/age/key.txt
              name: age-key
              readOnly: true
      volumes:
        - name: age-key
          secret:
            secretName: sops-age-key
