apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml

patches:
  - path: kustomize-controller-patch.yaml
    target:
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
  - path: synology-csi-controller-patch-mount.yaml # <-- ¡AÑADE ESTE NUEVO PATCH!
    target:
      kind: StatefulSet
      name: synology-csi-controller
      namespace: synology-csi # ¡Importante: el namespace donde está el StatefulSet!
