apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: synology-csi-controller
  namespace: synology-csi # ¡Importante: el namespace donde reside el StatefulSet!
spec:
  template:
    spec:
      volumes:
        - name: client-info # Nombre del volumen del Secret
          secret:
            secretName: synology-csi-client-info # Nombre de tu Secret de credenciales
            items:
              - key: client-info.yml # La clave dentro de tu Secret
                path: client-info.yaml # <-- ¡Aquí está la CORRECCIÓN! El nombre del archivo que el driver espera
      containers:
        - name: csi-plugin # El contenedor que necesita el archivo
          volumeMounts:
            - name: client-info
              mountPath: /etc/synology/ # Directorio donde se montará el Secret
              readOnly: true
              subPath: client-info.yaml # <-- ¡Y aquí otra CORRECCIÓN! Monta el archivo directamente
