apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-db-credentials
  namespace: linkding
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: linkding-db-secret
  data:
    - secretKey: LD_DB_USER
      remoteRef:
        key: /databases/linkding/LINKDING_DB_USER
    - secretKey: LD_DB_PASSWORD
      remoteRef:
        key: /databases/linkding/LINKDING_DB_PASSWORD
