apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: 11434
      name: http
  selector:
    app: ollama

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.kubernetes.io/ignore: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: "ollama.dimarco-server.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama-svc
                port:
                  name: http
  tls:
    - hosts:
        - "ollama.dimarco-server.site"
      secretName: ollama-tls
