apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-container-env
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  # data:
  #   - secretKey: DB_POSTGRESDB_USER
  #     remoteRef:
  #       key: n8n-db-username
  #   - secretKey: DB_POSTGRESDB_PASSWORD
  #     remoteRef:
  #       key: n8n-db-password
  # target:
  #   name: sparky-api-secrets
  data:
    - secretKey: DB_POSTGRESDB_USERNAME
      remoteRef:
        key: /databases/n8n/N8N_DB_USERNAME

    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: /databases/n8n/N8N_DB_PASSWORD
