apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networking.yaml
  - secret.yaml

configMapGenerator:
  - name: jellyfin-grafana-dashboard
    files:
      - jellyfin.json=dashboards/jellyfin.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: kyverno-grafana-dashboard
    files:
      - kyverno.json=dashboards/kyverno.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: vpa-recommendations-grafana-dashboard
    files:
      - vpa-recommendations.json=dashboards/vpa-recommendations.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
