apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediamanager-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
