apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
  labels:
    app: synology-csi
  annotations:
    managed-by: external-secrets
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: client-info-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        client-info.yml: |-
          clients:
            - host: {{ .dsm_host }}
              port: {{ .dsm_port }}
              username: {{ .dsm_username }}
              password: {{ .dsm_password }}
              https: {{ .dsm_https }}
  data:
    - secretKey: dsm_host
      remoteRef:
        key: /synology-csi/dsm_host
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: dsm_port
      remoteRef:
        key: /synology-csi/dsm_port
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: dsm_username
      remoteRef:
        key: /synology-csi/dsm_username
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: dsm_password
      remoteRef:
        key: /synology-csi/dsm_password
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: dsm_https
      remoteRef:
        key: /synology-csi/dsm_https
        conversionStrategy: Default
        decodingStrategy: None
