apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: client-info-secret
    creationPolicy: Owner
  data:
    - secretKey: client-info.yaml
      remoteRef:
        key: /synology-csi
        property: dsm_host
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: client-info.yaml
      remoteRef:
        key: /synology-csi
        property: dsm_port
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: client-info.yaml
      remoteRef:
        key: /synology-csi
      property: dsm_username
      conversionStrategy: Default
      decodingStrategy: None
    - secretKey: client-info.yaml
      remoteRef:
        key: /synology-csi
        property: dsm_password
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: client-info.yaml
      remoteRef:
        key: /synology-csi
        property: dsm_https
        conversionStrategy: Default
        decodingStrategy: None
