apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: synology-csi

resources:
  - namespace.yaml
  - controller.yaml
  - node.yaml
  - client-info.secret.sops.yaml
  - storage-class.yaml
