apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-data
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.79
  share: /volume1/Proxmox/databases
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4
