apiVersion: v1
kind: Service
metadata:
  name: memos
spec:
  ports:
    - port: 5230
      targetPort: 5230
      name: http
      protocol: TCP
  selector:
    app: memos
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memos-ingress
  namespace: memos
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.kubernetes.io/ignore: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: "memos.dimarco-server.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memos
                port:
                  name: http
  tls:
    - hosts:
        - "memos.dimarco-server.site"
      secretName: memos-tls
