apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparky-secrets
  namespace: sparky
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: sparky-secrets
  data:
    # Generar con: openssl rand -hex 32
    - secretKey: SPARKY_FITNESS_API_ENCRYPTION_KEY
      remoteRef:
        key: /sparky/SPARKY_FITNESS_API_ENCRYPTION_KEY
    # Generar con: openssl rand -base64 32
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: /sparky/BETTER_AUTH_SECRET
