apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-credentials
  namespace: immich
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: immich-db-credentials
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: /databases/immich/IMMICH_DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /databases/immich/IMMICH_DB_PASSWORD
