apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx # namespace donde vas a instalar
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.14.1" # o la versión que quieras usar
  values:
    controller:
      replicaCount: 1
      service:
        loadBalancerIP: 192.168.1.240
      admissionWebhooks:
        enabled: true
        patch:
          enabled: true
      config:
        # Enable underscores in headers to allow X-Emby-Authorization header
        enable-underscores-in-headers: "true"
        # Allow snippet annotations (configuration-snippet, server-snippet) for custom nginx config
        # Required for Jellyfin Apple TV authentication fix
        allow-snippet-annotations: "true"
        # Set annotations risk level to Critical to allow high-risk annotations like snippets
        annotations-risk-level: "Critical"
