apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  data:
    # IMPORTANTE: se repite el spec completo porque Kustomize no hace merge inteligente de arrays.
    # Si solo incluyéramos el item que queremos modificar (admin-password), se eliminaría el resto (como admin-user).
    # Por eso es necesario volver a declarar todos los valores deseados en spec.data.
    - secretKey: admin-password
      remoteRef:
        key: /grafana/GF_ADMIN_PASSWORD
    - secretKey: admin-user
      remoteRef:
        key: /grafana/GF_ADMIN_USER
