apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  data:
    - secretKey: admin-password
      remoteRef:
        key: /grafana/GF_ADMIN_PASSWORD 
