apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-exporter-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: jellyfin-exporter-secret
  data:
    - secretKey: JELLYFIN_TOKEN
      remoteRef:
        key: /jellyfin/JELLYFIN_API_TOKEN
