apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      protocol: TCP
      port: 8096
      targetPort: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.kubernetes.io/ignore: "true"
    # Anotación importante para NGINX para permitir archivos grandes (streaming)
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # Timeouts extendidos para streaming de video (previene desconexiones)
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # Buffer settings optimizados para streaming
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    # WebSocket support (Jellyfin requiere WebSockets para algunas funcionalidades)
    nginx.ingress.kubernetes.io/websocket-services: "jellyfin-svc"
    # Headers para reverse proxy (Jellyfin requiere estos para identificar IPs reales)
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    # NGINX Ingress Controller pasa todos los headers del cliente al upstream por defecto
    # incluyendo Authorization y X-Emby-Authorization (requiere enable-underscores-in-headers)
    # Fix para Apple TV: inyecta el parámetro App en el body JSON si falta en /Users/AuthenticateByName
    # Requiere annotations-risk-level: Critical en el nginx ingress controller
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $auth_path 0;
      if ($request_uri = "/Users/AuthenticateByName") {
        set $auth_path 1;
      }
      if ($request_method = POST) {
        set $auth_path "${auth_path}1";
      }
      access_by_lua_block {
        if ngx.var.uri == "/Users/AuthenticateByName" and ngx.var.request_method == "POST" then
          ngx.log(ngx.ERR, "[JELLYFIN-FIX] Intercepting auth request")
          ngx.req.read_body()
          local body = ngx.req.get_body_data()
          
          if body then
            ngx.log(ngx.ERR, "[JELLYFIN-FIX] Body length: " .. string.len(body))
            local cjson = require "cjson"
            local ok, json = pcall(cjson.decode, body)
            
            if ok and json then
              ngx.log(ngx.ERR, "[JELLYFIN-FIX] JSON parsed, App=" .. tostring(json.App))
              if not json.App or json.App == "" then
                json.App = "Apple TV"
                local new_body = cjson.encode(json)
                ngx.req.set_body_data(new_body)
                ngx.req.set_header("Content-Length", string.len(new_body))
                ngx.log(ngx.ERR, "[JELLYFIN-FIX] Injected App=Apple TV")
              end
            else
              ngx.log(ngx.ERR, "[JELLYFIN-FIX] Failed to parse JSON: " .. tostring(json))
            end
          else
            ngx.log(ngx.ERR, "[JELLYFIN-FIX] Body is nil or empty")
          end
        end
      }
spec:
  ingressClassName: nginx
  rules:
    - host: "jellyfin.dimarco-server.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin-svc
                port:
                  name: http
  tls:
    - hosts:
        - "jellyfin.dimarco-server.site"
      secretName: jellyfin-tls
