apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      protocol: TCP
      port: 8096
      targetPort: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.kubernetes.io/ignore: "true"
    # Anotación importante para NGINX para permitir archivos grandes (streaming)
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # Timeouts extendidos para streaming de video (previene desconexiones)
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # Buffer settings optimizados para streaming
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    # Reenvío explícito de headers de autenticación para clientes como Swiftfin
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Emby-Authorization $http_x_emby_authorization;
      proxy_set_header Authorization $http_authorization;
spec:
  ingressClassName: nginx
  rules:
    - host: "jellyfin.dimarco-server.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin-svc
                port:
                  name: http
  tls:
    - hosts:
        - "jellyfin.dimarco-server.site"
      secretName: jellyfin-tls
