apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      protocol: TCP
      port: 8096
      targetPort: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.kubernetes.io/ignore: "true"
    # Anotación importante para NGINX para permitir archivos grandes (streaming)
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # Timeouts extendidos para streaming de video (previene desconexiones)
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # Buffer settings optimizados para streaming
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    # WebSocket support (Jellyfin requiere WebSockets para algunas funcionalidades)
    nginx.ingress.kubernetes.io/websocket-services: "jellyfin-svc"
    # Headers para reverse proxy (Jellyfin requiere estos para identificar IPs reales)
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    # NGINX Ingress Controller pasa todos los headers del cliente al upstream por defecto
    # incluyendo Authorization y X-Emby-Authorization (requiere enable-underscores-in-headers)
    # Fix para Apple TV: inyecta el parámetro App en el body JSON si falta en /Users/AuthenticateByName
    # Requiere annotations-risk-level: Critical en el nginx ingress controller
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite_by_lua_block {
        -- Solo interceptamos si es la URL de auth y es POST
        if ngx.var.uri == "/Users/AuthenticateByName" and ngx.var.request_method == "POST" then
          -- Forzamos la lectura del body (esto habilita buffering automáticamente)
          ngx.req.read_body()
          local body = ngx.req.get_body_data()
          
          if body then
            local cjson = require "cjson"
            -- Usamos pcall para seguridad contra JSON inválido
            local ok, json = pcall(cjson.decode, body)
            
            -- Si falta App o está vacía, inyectamos "Apple TV"
            if ok and json and (not json.App or json.App == "") then
              json.App = "Apple TV"
              local new_body = cjson.encode(json)
              
              ngx.req.set_body_data(new_body)
              ngx.req.set_header("Content-Length", string.len(new_body))
            end
          end
        end
      }
spec:
  ingressClassName: nginx
  rules:
    - host: "jellyfin.dimarco-server.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin-svc
                port:
                  name: http
  tls:
    - hosts:
        - "jellyfin.dimarco-server.site"
      secretName: jellyfin-tls
