apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  # labels:
  #   app: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.41.0
          ports:
            - containerPort: 9090
          # volumeMounts:
          #   - name: data
          #     mountPath: /etc/linkding/data
          envFrom:
            - configMapRef:
                name: linkding-config-postgres
            - secretRef:
                name: linkding-db-secret
      restartPolicy: Always
      # volumes:
      #   - name: data
      #     persistentVolumeClaim:
      #       claimName: linkding-data
