apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding-ingress
  namespace: linkding
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  rules:
    - host: "linkding.dimarco-server.site"
  tls:
    - hosts:
        - "linkding.dimarco-server.site"
      secretName: linkding-tls
