apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-db-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: linkding-db-secret
  dataFrom:
    - find:
        path: /placeholder/path/for/linkding
