apiVersion: v1
kind: Secret
metadata:
    name: cifs-csi-credentials
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:LunxxFDwsprucQPTadg=,iv:YqbABRX9TGEemulUHWaDPwxAI61E0c1FOLCsFyaNC8s=,tag:o8nWnnpTj3i+uNiZpvZ0UA==,type:str]
    password: ENC[AES256_GCM,data:k2s9B/eB5pxFa8g=,iv:VfkfzLn8MG+rhzgvPN7VO3EJxESjEqPung2E7P7LknI=,tag:QjPfiIDtxOni+opcEfNwEg==,type:str]
sops:
    age:
        - recipient: age1y827m2r4ydam7xw0wv4s4tpjv63fwk0rnauzffdtt63pj4734c9q5w5g2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcjA1dytSbjEvZkdYMTdh
            S1JZQ3loYXhzZWdNdGI5QkVwWnlNNUE5aDFNClZzcVNOQkt5ZllYT09wanZaY0xC
            S29EQjBCMi82YVFueSt3aVludUh4L1UKLS0tIEo2bjZOMGlYdUF6Y1RFQW5BVFBw
            dzgrU00yU0lSNGlTTXNEK0NmMnUraW8K0pGP8mGwr95OWh5i64YwrQx7OsHZmF/B
            lOG58w1ablpB0aAOGGBtIn7p5OOxsI6GpXVFm4bIERh3TXrFmcnimw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T14:30:30Z"
    mac: ENC[AES256_GCM,data:oKZPSHKt8lUovjbJjfL2bdK11W/gwaYJ53v0jPgsINPz1Zb0NcWx/aRI019JsQvJb1O/iqhNI9FIVhHEhyd4ZeuPdb1adNyk99+AkaLa3eJMzElz4Aw0jfaw7ll4U4uOtDmiDcJyE/P5mLbaIqQMx8NYDn7ieIP40qRMAUNNZMY=,iv:tq20TdXPdNGKcwNoMLGNXN3xClH1FRA6fhfVtDhVhF4=,tag:YfiGRVf5yHO500ryW8tEZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
