apiVersion: v1
kind: Service
metadata:
  name: plex-svc
spec:
  selector:
    app: plex
  ports:
    - name: http
      protocol: TCP
      port: 32400
      targetPort: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.kubernetes.io/ignore: "true"
    # Anotación importante para NGINX para permitir archivos grandes (streaming)
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # Timeouts extendidos para streaming de video (previene desconexiones)
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # Buffer settings optimizados para streaming
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
spec:
  ingressClassName: nginx
  rules:
    - host: "plex.dimarco-server.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex-svc
                port:
                  name: http
  tls:
    - hosts:
        - "plex.dimarco-server.site"
      secretName: plex-tls
