apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-claim-secret
  namespace: plex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: plex-claim-secret
    creationPolicy: Owner
  data:
    - secretKey: PLEX_CLAIM
      remoteRef:
        key: /plex/PLEX_CLAIM
