# --- Volumen para la LIBRERÍA DE MEDIA (compartido con Jellyfin) ---
# Creamos un PV separado que apunta al mismo path de NFS que Jellyfin
# Ambos PVs apuntan al mismo almacenamiento físico, permitiendo compartir los datos
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
  labels:
    app: shared-media
    type: media-library
spec:
  storageClassName: ""
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.79
    path: "/volume1/Proxmox/Media"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: plex-media-pv
---
# --- Volumen para la CONFIGURACIÓN de Plex ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# --- Volumen para TRANSCODING (mejores prácticas: storage local, pero usamos NFS por consistencia) ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode-pvc
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
